spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/cars_project
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    host: smtp.gmail.com
    username: sagarparmar.test@gmail.com
    password: zlpcuaqemrqwrbjr
    port: 587

cars:
  initialize-default-setup: false
